version: '3'

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - URL=lotr.ericpaulsen.io
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN="route53"
      - EMAIL=eric@coder.com
      - DHLEVEL=4096
    volumes:
      - "~/letsencrypt:/config"
    restart: unless-stopped
  nginx:
    container_name: nginx
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - "nginx:/etc/nginx"
      - "~/letsencrypt:/letsencrypt/"
  coder:
    hostname: coder
    image: codercom/coder:1.25.1
    container_name: coder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.coder:/var/run/coder
    ports:
      - 7080:7080
    environment:
      - DEVURL_HOST="*.lotr.ericpaulsen.io"